public class Hosts extends Person {

	private Phrases phrase;
	private String[] phraseList = {
			"A GOOD FIT",
			"A GREAT BUY",
			"AHEAD OF THE GAME",
			"ALL OPERATORS ARE BUSY",
			"AS RED AS A BEET",
			"AVOID THE PITFALLS",
			"A GRIPPING PAGE TURNER",
			"ALL KINDS OF THINGS TO DO",
			"BACK TO SQUARE ONE",
			"BACK TO BASICS",
			"BONJOUR",
			"BUILT TO LAST",
			"COAST TO COAST",
			"COMING UNGLUED",
			"CALL FOR DIRECTIONS",
			"COMING ON LIKE GANGBUSTERS",
			"CLOSED FOR RENOVATIONS",
			"CULTURAL CENTER OF THE COUNTRY",
			"DO YOU SPEAK FRENCH?",
			"DRAWING A BLANK",
			"DONT SPOIL YOUR DINNER",
			"EXPLAIN YOURSELF",
			"FADING AWAY",
			"FAMILY FUN",
			"FALL IN LOVE WITH THIS CITY",
			"FIRE UP THE GRILL",
			"FULL BODIED FLAVOR",
			"GIVE ME A HINT",
			"GOING HALFWAY",
			"GOING THE DISTANCE",
			"GROWING UP",
			"HAVING A GREEN THUMB",
			"HAIL TO THE CHIEF",
			"HAVE A BITE TO EAT",
			"HERE WE GO AGAIN",
			"I WAS BORN READY",
			"IN THE LIMELIGHT",
			"IT NEVER EVEN CROSSED MY MIND",
			"ITS ALL IN A DAYS WORK",
			"IVE GOT A HUNCH",
			"ITS A DIRTY SHAME",
			"IVE LEARNED MY LESSON",
			"JUST CHILLIN",
			"KEEP YOUR COOL",
			"KEEP YOUR NOSE CLEAN",
			"LAY IT ON THICK",
			"MIX AND MATCH",
			"MINT CONDITION",
			"NEVER SAY NEVER",
			"NEVER IN MY WILDEST DREAMS",
			"ONCE IN A BLUE MOON",
			"OPEN UP A CAN OF WORMS",
			"PICTURE THIS",
			"PICK A CARD ANY CARD",
			"PURE COINCIDENCE",
			"RAISING CAIN",
			"RAKE OVER THE COALS",
			"READY WHEN YOU ARE",
			"RETURN TO PARADISE",
			"SEASON TO TASTE",
			"SEATING IS LIMITED",
			"SHAKEN NOT STIRRED",
			"SHARE AND SHARE ALIKE",
			"STOP BUILDING CASTLES IN THE SKY",
			"STANDING ROOM ONLY",
			"SOME ASSEMBLY REQUIRED",
			"SWEET SIXTEEN AND NEVER BEEN KISSED",
			"THE TRUTH SHALL SET YOU FREE",
			"TAKE CARE",
			"TIME FOR MIRACLES",
			"THANKS A MILLION",
			"THEY NEVER KNEW WHAT HIT THEM",
			"THROWING YOUR MONEY AROUND",
			"TWO OF A KIND",
			"UP AND COMING",
			"WALK IT OFF",
			"WITHOUT SPENDING AN ARM AND A LEG",
			"WISH YOU WERE HERE",
			"WORK SMARTER NOT HARDER",
			"WAY TO GO",
			"YOURE PUSHING MY BUTTONS",
			"YOUR MESSAGE HAS BEEN SENT",
			"YOUR HEART IS IN THE RIGHT PLACE",
			"YOU TOOK THE WORDS RIGHT OUT OF MY MOUTH",
			"ZOOM IN",
	};

	public Hosts(String fname) {
		super(fname);
		phrase = new Phrases();
	}

	public Hosts(String fname, String lname) {
		super(fname, lname);
		phrase = new Phrases();
	}

	public Phrases getPhrase() {
		return phrase;
	}

	public void randomizePhrase() {
		phrase.setPhrase(phraseList[(int) (Math.random() * phraseList.length)]);
		phrase.generatePhrase();
	}
}
